---
title: "mODa14"
description: "Draft version of the Proceedings Papers"
output: distill::distill_article
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

```{r results='asis', echo=FALSE}

cat("<div style='margin-bottom:18px'><div style='display: flex; align-items: center; gap:15px;'><span style='font-size:18px; font-weight:bold;'>Bect Julien</span><span style='font-size:14px;'><a href='DPPpapers/Bect.pdf' target='_blank'>click here for the proceedings paper</a></span></div><div style='font-size:14px;'>L2S / CentraleSupélec</div></div><br>")
cat("<div style='margin-bottom:18px'><div style='display: flex; align-items: center; gap:15px;'><span style='font-size:18px; font-weight:bold;'>Frieri Rosamarie</span><span style='font-size:14px;'><a href='DPPpapers/Frieri.pdf' target='_blank'>click here for the proceedings paper</a></span></div><div style='font-size:14px;'>University of Bologna</div></div><br>")
cat("<div style='margin-bottom:18px'><div style='display: flex; align-items: center; gap:15px;'><span style='font-size:18px; font-weight:bold;'>Gautier Athénaïs</span><span style='font-size:14px;'><a href='DPPpapers/Gautier.pdf' target='_blank'>click here for the proceedings paper</a></span></div><div style='font-size:14px;'>ONERA</div></div><br>")
cat("<div style='margin-bottom:18px'><div style='display: flex; align-items: center; gap:15px;'><span style='font-size:18px; font-weight:bold;'>Kang Lulu</span><span style='font-size:14px;'><a href='DPPpapers/Kang.pdf' target='_blank'>click here for the proceedings paper</a></span></div><div style='font-size:14px;'>University of Massachusetts Amherst</div></div><br>")
cat("<div style='margin-bottom:18px'><div style='display: flex; align-items: center; gap:15px;'><span style='font-size:18px; font-weight:bold;'>Lamberti Justin</span><span style='font-size:14px;'><a href='DPPpapers/Lamberti.pdf' target='_blank'>click here for the proceedings paper</a></span></div><div style='font-size:14px;'>TU Dortmund University</div></div><br>")
cat("<div style='margin-bottom:18px'><div style='display: flex; align-items: center; gap:15px;'><span style='font-size:18px; font-weight:bold;'>Leonov Sergei</span><span style='font-size:14px;'><a href='DPPpapers/Leonov.pdf' target='_blank'>click here for the proceedings paper</a></span></div><div style='font-size:14px;'>CSL Behring</div></div><br>")
cat("<div style='margin-bottom:18px'><div style='display: flex; align-items: center; gap:15px;'><span style='font-size:18px; font-weight:bold;'>Malevich Nadja</span><span style='font-size:14px;'><a href='DPPpapers/Malevich.pdf' target='_blank'>click here for the proceedings paper</a></span></div><div style='font-size:14px;'>Universität Münster</div></div><br>")
cat("<div style='margin-bottom:18px'><div style='display: flex; align-items: center; gap:15px;'><span style='font-size:18px; font-weight:bold;'>Müller Christine</span><span style='font-size:14px;'><a href='DPPpapers/Muller.pdf' target='_blank'>click here for the proceedings paper</a></span></div><div style='font-size:14px;'>TU Dortmund</div></div><br>")
cat("<div style='margin-bottom:18px'><div style='display: flex; align-items: center; gap:15px;'><span style='font-size:18px; font-weight:bold;'>Parker Ben</span><span style='font-size:14px;'><a href='DPPpapers/Parker.pdf' target='_blank'>click here for the proceedings paper</a></span></div><div style='font-size:14px;'>Brunel, University of London</div></div><br>")
cat("<div style='margin-bottom:18px'><div style='display: flex; align-items: center; gap:15px;'><span style='font-size:18px; font-weight:bold;'>Pronzato Luc</span><span style='font-size:14px;'><a href='DPPpapers/Pronzato.pdf' target='_blank'>click here for the proceedings paper</a></span></div><div style='font-size:14px;'>CNRS</div></div><br>")
cat("<div style='margin-bottom:18px'><div style='display: flex; align-items: center; gap:15px;'><span style='font-size:18px; font-weight:bold;'>Riccomagno Eva</span><span style='font-size:14px;'><a href='DPPpapers/Riccomagno.pdf' target='_blank'>click here for the proceedings paper</a></span></div><div style='font-size:14px;'>University of Genova</div></div><br>")
cat("<div style='margin-bottom:18px'><div style='display: flex; align-items: center; gap:15px;'><span style='font-size:18px; font-weight:bold;'>Rosenberger Bill</span><span style='font-size:14px;'><a href='DPPpapers/Rosenberger.pdf' target='_blank'>click here for the proceedings paper</a></span></div><div style='font-size:14px;'>George Mason University</div></div><br>")
cat("<div style='margin-bottom:18px'><div style='display: flex; align-items: center; gap:15px;'><span style='font-size:18px; font-weight:bold;'>Sada Allo Maider</span><span style='font-size:14px;'><a href='DPPpapers/SadaAllo.pdf' target='_blank'>click here for the proceedings paper</a></span></div><div style='font-size:14px;'>Universidad Pública de Navarra</div></div><br>")
cat("<div style='margin-bottom:18px'><div style='display: flex; align-items: center; gap:15px;'><span style='font-size:18px; font-weight:bold;'>Sverdlov Alex</span><span style='font-size:14px;'><a href='DPPpapers/Sverdlov.pdf' target='_blank'>click here for the proceedings paper</a></span></div><div style='font-size:14px;'>Novartis</div></div><br>")
cat("<div style='margin-bottom:18px'><div style='display: flex; align-items: center; gap:15px;'><span style='font-size:18px; font-weight:bold;'>Wang Yaping</span><span style='font-size:14px;'><a href='DPPpapers/Wang3.pdf' target='_blank'>click here for the proceedings paper</a></span></div><div style='font-size:14px;'>East China Normal University</div></div><br>")
cat("<div style='margin-bottom:18px'><div style='display: flex; align-items: center; gap:15px;'><span style='font-size:18px; font-weight:bold;'>Youssef Noha</span><span style='font-size:14px;'><a href='DPPpapers/Youssef.pdf' target='_blank'>click here for the proceedings paper</a></span></div><div style='font-size:14px;'>The American University in Cairo</div></div><br>")
cat("<div style='margin-bottom:18px'><div style='display: flex; align-items: center; gap:15px;'><span style='font-size:18px; font-weight:bold;'>Yu Jun</span><span style='font-size:14px;'><a href='DPPpapers/Yu.pdf' target='_blank'>click here for the proceedings paper</a></span></div><div style='font-size:14px;'>Beijing Institute of Technology</div></div><br>")
cat("<div style='margin-bottom:18px'><div style='display: flex; align-items: center; gap:15px;'><span style='font-size:18px; font-weight:bold;'>Zhou Yongdao</span><span style='font-size:14px;'><a href='DPPpapers/Zhou.pdf' target='_blank'>click here for the proceedings paper</a></span></div><div style='font-size:14px;'>Nankai University, China</div></div><br>")

```
